backendapp/urls.py
from django.urls import path
from backendapp.views import *


urlpatterns = [
    path('', index, name='dashboard'),

    ## Transaction ##
    path('transactions/', TransactionListView.as_view(), name='transactions'),
    path('transactions/create/', TransactionCreateView.as_view(), name='transaction-create'),
    path('transactions/delete/<int:pk>/', TransactionDeleteView.as_view(), name='transaction-delete'),
    path('transactions/update/<int:pk>/', TransactionUpdateView.as_view(), name='transaction-update'),
        
    ## Transfer ##
    path('transfers/', TransferListView.as_view(), name='transfers'),
    path('transfers/create/', TransferCreateView.as_view(), name='transfer-create'),
    path('transfers/delete/<int:pk>/', TransferDeleteView.as_view(), name='transfer-delete'),
    path('transfers/update/<int:pk>/', TransferUpdateView.as_view(), name='transfer-update'),
    
    ## Account ##
    path('accounts/', AccountListView.as_view(), name='accounts'),
    path('accounts/create/', AccountCreateView.as_view(), name='account-create'),
    path('accounts/delete/<int:pk>/', AccountDeleteView.as_view(), name='account-delete'),
    path('accounts/update/<int:pk>/', AccountUpdateView.as_view(), name='account-update'),
    path('account/update-status/<int:pk>/', update_account_status, name='update-account-status'),
    
    ## Budget ##
    path('budgets/', BudgetListView.as_view(), name='budgets'),
    path('budgets/create/', BudgetCreateView.as_view(), name='budget-create'),
    path('budgets/delete/<int:pk>/', BudgetDeleteView.as_view(), name='budget-delete'),
    path('budgets/update/<int:pk>/', BudgetUpdateView.as_view(), name='budget-update'),
    path('budgets/update-status/<int:pk>/', update_budget_status, name='update-budget-status'),

    ## Category ##
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('categories/create/', CategoryCreateView.as_view(), name='category-create'),
    path('categories/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category-delete'),
    path('categories/update/<int:pk>/', CategoryUpdateView.as_view(), name='category-update'),
    path('categories/update-status/<int:pk>/', update_category_status, name='update-category-status'),
    
    ## Currency ##
    path('currencies/', CurrencyView.as_view(), name='currencies'),
    
    ## User ##
    path('users/', user, name='users'),
    
    path('get-csrf-token/', get_csrf_token, name='get-csrf-token')
]

wealth_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backendapp.urls')),
]

backendapp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.db.models import Sum, F
from decimal import Decimal


class Category(models.Model):
    TYPE_CHOISES = (
        ('expense', 'Dépense'),
        ('income', 'Révenu')
    )
    
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=20, choices=TYPE_CHOISES)
    description = models.TextField(null=True, blank=True)
    icon = models.CharField(max_length=30)
    status = models.SmallIntegerField(default=0, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='category_created')
    updated_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='category_updated', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    
    def __str__(self):
        return f"{self.name} - ({self.type})"
    
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        

class Transaction(models.Model):
    amount = models.DecimalField(max_digits=18, decimal_places=3, default=0.00, null=True)
    account = models.ForeignKey('Account', null=True, blank=True, on_delete=models.DO_NOTHING, related_name='account_transactions')
    description = models.TextField(null=True, blank=True)
    date = models.DateField(default=datetime.now)
    photo = models.FileField(upload_to="transactions_photos/", blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_transactions')
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, related_name='category_transactions')
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='transaction_created')
    updated_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='transaction_updated', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    
    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name} (Mt. {self.amount})"
    
    class Meta:
        verbose_name = 'Transaction'
        verbose_name_plural = 'Transactions'
    

class Budget(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    total_amount = models.DecimalField(max_digits=18, decimal_places=3, default=0.00, null=True)
    start_at = models.DateTimeField()
    end_at = models.DateTimeField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    status = models.SmallIntegerField(default=0, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_budget')
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='budget_created')
    updated_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='budget_updated', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    
    def __str__(self):
        return f"{self.title} - (Initial: {self.total_amount})"
        
    class Meta:
        verbose_name = 'Budget'
        verbose_name_plural = 'Budgets'
        unique_together = ('user', 'category')
    
    
class Account(models.Model):
    TYPE_CHOICES = (
        ('orange_money', 'Orange Money'),
        ('mobile_money', 'Mobile Money'),
        ('bank', 'Banque'),
        ('others', 'Autres')
    )
    
    name = models.CharField(max_length=50)
    type = models.CharField(max_length=50, choices=TYPE_CHOICES)
    balance = models.DecimalField(max_digits=18, decimal_places=3)
    description = models.TextField(null=True, blank=True)
    currency = models.ForeignKey('Currency', on_delete=models.CASCADE, related_name='currency_accounts')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_accounts')
    status = models.SmallIntegerField(default=1, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='account_created')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='account_updated', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    
    def __str__(self):
        return f"{self.name} - (Mt. Actuel: {self.current_balance()})"
    
    def current_balance(self):
        transactions = Transaction.objects.filter(account=self)
        total_debit_income = transactions.filter(category__type='income', amount__lt=0).aggregate(total=Sum(F('amount')))['total'] or Decimal('0.00')
        total_debit_expense = transactions.filter(category__type='expense', amount__lt=0).aggregate(total=Sum(F('amount')))['total'] or Decimal('0.00')
        total_credit = transactions.filter(amount__gt=0).aggregate(total=Sum('amount'))['total'] or Decimal('0.00')
        return self.balance + total_credit + total_debit_income + total_debit_expense
    
    def deduce_balance(self, amount):
        self.balance -= Decimal(amount)
        self.save()
        
        return str(self.balance)
    
    def increase_balance(self, amount):
        self.balance += Decimal(amount)
        self.save()
        
        return str(self.balance)
    
    class Meta:
        verbose_name = 'Account'
        verbose_name_plural = 'Accounts'
    
    
class Transfer(models.Model):#fait le
    sender_account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='sender_account')
    recipient_account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='recipient_account')
    amount = models.DecimalField(max_digits=18, decimal_places=3)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_transfer')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='transfer_created')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='transfer_updated', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    
    def __str__(self):
        return f"{self.sender_account.account_number} vers {self.recipient_account.account_number}"
    
    class Meta:
        verbose_name = 'Transfer'
        verbose_name_plural = 'Transfers'
    

class Currency(models.Model):
    name = models.CharField(max_length=20)
    code = models.CharField(max_length=10)
    status = models.SmallIntegerField(default=1, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='currency_created')
    updated_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='currency_updated', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return f"{self.name} - ({self.code})"
    
    class Meta:
        verbose_name = 'Currency'
        verbose_name_plural = 'Currencies'
      

backendapp/forms.py
from django import forms
from backendapp.models import *


class CategoryForm(forms.ModelForm):
    
    class Meta:
        model = Category
        exclude = ['status', 'created_by', 'updated_by', 'created_at', 'updated_at']
        
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Veuillez entrer un nom de categorie'}),
            'type': forms.Select(attrs={'class': 'form-select'}, choices=Category.TYPE_CHOISES),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Laisser une description...', 'style': 'height: 100px'}),
            'icon': forms.TextInput(attrs={'type': 'hidden'})
        }
    
    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        
        
class CurrencyForm(forms.ModelForm):
    
    class Meta:
        model = Currency
        exclude = ['status', 'created_by', 'updated_by', 'created_at', 'updated_at']
        
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Veuillez entrer un nom'}),
            'code': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Veuillez entrer le code'})
        }
        

class BudgetForm(forms.ModelForm):
    
    class Meta:
        model = Budget
        exclude = ['user', 'created_by', 'updated_by', 'created_at', 'updated_at']
        
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Veuillez entrer une désignation'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Laisser une description...', 'style': 'height: 100px'}),
            'total_amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'start_at': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'end_at': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'category': forms.Select(attrs={'class': 'form-select'}, choices=[(category.id, category.name) for category in Category.objects.filter(type='expense', status=1)])
        }
    
    
class TransactionForm(forms.ModelForm):
    
    class Meta:
        model = Transaction
        exclude = ['user', 'created_by', 'updated_by', 'created_at', 'updated_at']
        
        widgets = {
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Laisser une description...', 'style': 'height: 100px'}),
            'category': forms.Select({'class': 'form-select'}, choices=[]),
            'account': forms.Select({'class': 'form-select'}, choices=[]),
            'date': forms.DateTimeInput(attrs={'class': 'form-control input-with-bottom-line', 'id': 'dateEnd', 'type': 'date'}),
            'photo': forms.ClearableFileInput(
                attrs={'class': 'form-control input-with-bottom-line', 'type': 'file'})
        }
                
    def get_categories(self):
        return Category.objects.filter(status=1)
    
    
class AccountForm(forms.ModelForm):
    
    class Meta:
        model = Account
        exclude = ['status', 'user', 'created_by', 'updated_by', 'created_at', 'updated_at']
                
        widgets = {
            'name': forms.TextInput({'class': 'form-control', 'placeholder': 'Veuillez rentrez le nom (désignation)'}),
            'type': forms.Select(attrs={'class': 'form-select'}, choices=Account.TYPE_CHOICES),
            'balance': forms.NumberInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Laisser une description...', 'style': 'height: 100px'}),
            'currency': forms.Select(attrs={'class': 'form-select'}, choices=[(currency.id, currency.name) for currency in Currency.objects.filter(status=1)]),
        }
        
        
class TransferForm(forms.ModelForm):
    
    class Meta:
        model = Transfer
        exclude = ['user', 'created_by', 'updated_by', 'created_at', 'updated_at']
        
        widgets = {
            'sender_account': forms.Select(attrs={'class': 'form-select'}, choices=[]),
            'recipient_account': forms.Select(attrs={'class': 'form-select'}, choices=[]),
            'amount': forms.NumberInput(attrs={'class': 'form-control'})
        }

backendapp/templates/backendapp/pages/currency/currencies.html
{% extends 'backendapp/base.html' %}

{% load static %}

{% block main_content %}
<div class="container-fluid p-0">
    <h1 class="h3 mb-3">Gestion des dévises</h1>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body px-4 overflow-x-auto">
                    <div>
                        <form id="currency-form" method="post" action="{% url 'currencies' %}">
                            {% csrf_token %}
                        
                            <div class="row mb-4">
                                <div class="col-md-6 mb-3">
                                    <label for="id_name">Nom:</label>
                                    {{ form.name }}
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="id_name">Code:</label>
                                    {{ form.code }}
                                </div>
                                
                                <div class="d-flex flex-row-reverse  bd-highlight mt-2">
                                    <button type="submit" id="submit-button" class="btn btn-primary" onclick="submitCreateForm(event)">
                                        <i class="align-middle" data-feather="plus-circle"></i>
                                        Ajouter la dévise
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>

                    <div class="dropdown-divider mb-5"></div>

                    {% include 'backendapp/partials/messages.html' %}

                    <table class="shadow table table-hover table-striped">
                        <thead class="table-dark">
                            <tr>
                                <th class="text-center">N°#</th>
                                <th class="text-center">Code</th>
                                <th class="text-center">Désignation</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for currency in page_obj %}
                                <tr>
                                    <td class="text-center">{{ currency.id }}</td>
                                    
                                    <td class="text-center">{{ currency.code }}</td>

                                    <td class="text-center">
                                        <span>
                                            <i class="align-middle" data-feather="dollar-sign"></i>
                                        </span>
                                        {{ currency.name }}
                                    </td>

                                    <td class="text-center">
                                        <div class="dropdown">
                                            <button class="btn btn-secondary dropdown-toggle" type="button" id="currency-action" data-bs-toggle="dropdown" aria-expanded="false">
                                                Action
                                            </button>
                                            <ul class="dropdown-menu p-0" aria-labelledby="currency-action">                                                
                                                <li><button class="dropdown-item"  onclick="updateCurrency({{ currency.id }})">Modifier</button></li>
                                                
                                                <li>
                                                    <button class="dropdown-item bg-danger text-white" onclick="deleteCurrencyModal({{ currency.id }})">Supprimer</button>

                                                    <form id="delete-currency-form-{{ currency.id }}" method="post" action="{% url 'currencies' %}">
                                                        <input type="hidden" name="csrfmiddlewaretoken" value="">
                                                        <input type="hidden" name="currency_id" value="{{ currency.id }}">
                                                    </form>
                                                </li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="5" class="text-center">
                                        <span class="badge bg-warning">Aucune données trouvées dans la BDD</span>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                    <!-- pagination HTML -->
                    <nav>
                        <ul class="pagination pagination-sm justify-content-end">
                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a href="?page={{ page_obj.previous_page_number }}" class="page-link">previous</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a href="" class="page-link">previous</a>
                                </li>
                            {% endif %}

                            {% for page in page_obj.paginator.page_range %}
                                <li class="page-item {% if page_obj.number == page %}active" aria-current="page"{% endif %}">
                                    <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                                </li>
                            {% endfor %}

                            {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a href="?page={{ page_obj.next_page_number }}" class="page-link">next</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a href="" class="page-link">next</a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                    <!-- END pagination HTML -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main_content %}


{% block app_scripts %}
<script>
    function submitCreateForm(event) {
        event.preventDefault()
        
        const buttonLabel = $('#submit-button').text().trim()
        const data = $('#currency-form').serialize()
        
        if (buttonLabel === "Ajouter la dévise") {
            $.ajax({
                type: 'POST',
                url: "{% url 'currencies' %}",
                data: data,
                dataType: 'json',
                success: function (data) {
                    const url = "{% url 'currencies' %}"
                    $(location).attr('href', url)
                },
                error: function (error) {
                    console.log(error)
                }
            })
        }

        if (buttonLabel === "Modifier") {
            Swal.fire({
                title: "Veuillez confirmer ?",
                text: "Voulez-vous vraiment effectuez cette modification...",
                icon: "info",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                cancelButtonText: "Non",
                confirmButtonText: "Oui"
            }).then((result) => {
                if (result.isConfirmed) {
                    submmitUpdateForm()
                }
            })

            function submmitUpdateForm() {
                $.ajax({
                    type: 'GET',
                    url: "{% url 'get-csrf-token' %}",
                    success: function (data) {
                        let token = data.csrf_token
        
                        const currencyId = $('#currency_id').val()
                        const name = $('#id_name').val()
                        const code = $('#id_code').val()
                        
                        console.log('id', currencyId)
                        console.log('name', name)
                        console.log('code', code)
                        $.ajax({
                            type: 'PATCH',
                            url: "{% url 'currencies' %}" + `?currency_id=${currencyId}&name=${name}&code=${code}`,
                            beforeSend: function (xhr) {
                                xhr.setRequestHeader('X-CSRFToken', token)
                            },
                            success: function (data) {
                                const url = "{% url 'currencies' %}"
                                $(location).attr('href', url)
                            },
                            error: function (error) {
                                console.log(error)
                            }
                        })
                    },
                    error: function (error) {
                        console.log(error)
                    }
                })
            }
        }
    }

    function updateCurrency(currencyId) {
        $('#submit-button').html('<i class="align-middle" data-feather="edit"></i>Modifier')
        
        const url = {% url 'currencies' %} + `?currencyId=${currencyId}`

        $.ajax({
            type: 'GET',
            url: url,
            success: function (data) {
                $('[name="name"]').val(data.name)
                $('[name="code"]').val(data.code)
                
                const currencyInput = $('<input>').attr('type', 'hidden').attr('name', 'currency_id').attr('id', 'currency_id').val(currencyId)
                $('#currency-form').append(currencyInput)
            },
            error: function (error) {
                console.log(error)
            }
        })
    }
    
    function deleteCurrencyModal(currencyId) {
        Swal.fire({
            title: "Etes vous sûr ?",
            text: "Confirmez si vous voulez effectuez cette action...",
            icon: "warning",
            showCancelButton: true,
            confirmButtonColor: "#3085d6",
            cancelButtonColor: "#d33",
            cancelButtonText: "Non",
            confirmButtonText: "Oui"
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    type: 'GET',
                    url: "{% url 'get-csrf-token' %}",
                    success: function (data) {
                        let token = data.csrf_token

                        const form = $(`#delete-currency-form-${ currencyId }`)
                        $(form.children()[0]).val(token)

                        data = $(`#delete-currency-form-${ currencyId }`).serialize()
                        
                        $.ajax({
                            type: 'DELETE',
                            url: "{% url 'currencies' %}" + `?currency_id=${currencyId}`,
                            data: data,
                            dataType: 'json',
                            beforeSend: function (xhr) {
                                xhr.setRequestHeader('X-CSRFToken', token)
                            },
                            success: function (data) {
                                const url = "{% url 'currencies' %}"
                                $(location).attr('href', url)
                            },
                            error: function (error) {
                                console.log(error)
                            }
                        })
                    },
                    error: function (error) {
                        console.log(error)
                    }
                })                
            }
        })
    }

    function getCSRFToken() {
        $.ajax({
            type: 'GET',
            url: "{% url 'get-csrf-token' %}",
            success: function (data) {
                return data.csrf_token
            },
            error: function (error) {
                console.log(error)
            }
        })
    }
</script>
{% endblock app_scripts %}