backendapp/urls.py
from django.urls import path
from backendapp.views import *


urlpatterns = [
    path('', index, name='dashboard'),

    ## Transaction ##
    path('transactions/', TransactionListView.as_view(), name='transactions'),
    path('transactions/create/', TransactionCreateView.as_view(), name='transaction-create'),
    path('transactions/delete/<int:pk>/', TransactionDeleteView.as_view(), name='transaction-delete'),
    path('transactions/update/<int:pk>/', TransactionUpdateView.as_view(), name='transaction-update'),
        
    ## Transfer ##
    path('transfers/', TransferListView.as_view(), name='transfers'),
    path('transfers/create/', TransferCreateView.as_view(), name='transfer-create'),
    path('transfers/delete/<int:pk>/', TransferDeleteView.as_view(), name='transfer-delete'),
    path('transfers/update/<int:pk>/', TransferUpdateView.as_view(), name='transfer-update'),
    
    ## Account ##
    path('accounts/', AccountListView.as_view(), name='accounts'),
    path('accounts/create/', AccountCreateView.as_view(), name='account-create'),
    path('accounts/delete/<int:pk>/', AccountDeleteView.as_view(), name='account-delete'),
    path('accounts/update/<int:pk>/', AccountUpdateView.as_view(), name='account-update'),
    path('account/update-status/<int:pk>/', update_account_status, name='update-account-status'),
    
    ## Budget ##
    path('budgets/', BudgetListView.as_view(), name='budgets'),
    path('budgets/create/', BudgetCreateView.as_view(), name='budget-create'),
    path('budgets/delete/<int:pk>/', BudgetDeleteView.as_view(), name='budget-delete'),
    path('budgets/update/<int:pk>/', BudgetUpdateView.as_view(), name='budget-update'),
    path('budgets/update-status/<int:pk>/', update_budget_status, name='update-budget-status'),

    ## Category ##
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('categories/create/', CategoryCreateView.as_view(), name='category-create'),
    path('categories/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category-delete'),
    path('categories/update/<int:pk>/', CategoryUpdateView.as_view(), name='category-update'),
    path('categories/update-status/<int:pk>/', update_category_status, name='update-category-status'),
    
    ## Currency ##
    path('currencies/', CurrencyView.as_view(), name='currencies'),
    
    ## User ##
    path('users/', user, name='users'),
    
    path('get-csrf-token/', get_csrf_token, name='get-csrf-token')
]

wealth_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backendapp.urls')),
]

backendapp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.db.models import Sum, F
from decimal import Decimal


class Category(models.Model):
    TYPE_CHOISES = (
        ('expense', 'Dépense'),
        ('income', 'Révenu')
    )
    
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=20, choices=TYPE_CHOISES)
    description = models.TextField(null=True, blank=True)
    icon = models.CharField(max_length=30)
    status = models.SmallIntegerField(default=0, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='category_created')
    updated_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='category_updated', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    
    def __str__(self):
        return f"{self.name} - ({self.type})"
    
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        

class Transaction(models.Model):
    amount = models.DecimalField(max_digits=18, decimal_places=3, default=0.00, null=True)
    account = models.ForeignKey('Account', null=True, blank=True, on_delete=models.DO_NOTHING, related_name='account_transactions')
    description = models.TextField(null=True, blank=True)
    date = models.DateField(default=datetime.now)
    photo = models.FileField(upload_to="transactions_photos/", blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_transactions')
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, related_name='category_transactions')
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='transaction_created')
    updated_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='transaction_updated', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    
    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name} (Mt. {self.amount})"
    
    class Meta:
        verbose_name = 'Transaction'
        verbose_name_plural = 'Transactions'
    

class Budget(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    total_amount = models.DecimalField(max_digits=18, decimal_places=3, default=0.00, null=True)
    start_at = models.DateTimeField()
    end_at = models.DateTimeField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    status = models.SmallIntegerField(default=0, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_budget')
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='budget_created')
    updated_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='budget_updated', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    
    def __str__(self):
        return f"{self.title} - (Initial: {self.total_amount})"
        
    class Meta:
        verbose_name = 'Budget'
        verbose_name_plural = 'Budgets'
        unique_together = ('user', 'category')
    
    
class Account(models.Model):
    TYPE_CHOICES = (
        ('orange_money', 'Orange Money'),
        ('mobile_money', 'Mobile Money'),
        ('bank', 'Banque'),
        ('others', 'Autres')
    )
    
    name = models.CharField(max_length=50)
    type = models.CharField(max_length=50, choices=TYPE_CHOICES)
    balance = models.DecimalField(max_digits=18, decimal_places=3)
    description = models.TextField(null=True, blank=True)
    currency = models.ForeignKey('Currency', on_delete=models.CASCADE, related_name='currency_accounts')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_accounts')
    status = models.SmallIntegerField(default=1, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='account_created')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='account_updated', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    
    def __str__(self):
        return f"{self.name} - (Mt. Actuel: {self.current_balance()})"
    
    def current_balance(self):
        transactions = Transaction.objects.filter(account=self)
        total_debit_income = transactions.filter(category__type='income', amount__lt=0).aggregate(total=Sum(F('amount')))['total'] or Decimal('0.00')
        total_debit_expense = transactions.filter(category__type='expense', amount__lt=0).aggregate(total=Sum(F('amount')))['total'] or Decimal('0.00')
        total_credit = transactions.filter(amount__gt=0).aggregate(total=Sum('amount'))['total'] or Decimal('0.00')
        return self.balance + total_credit + total_debit_income + total_debit_expense
    
    def deduce_balance(self, amount):
        self.balance -= Decimal(amount)
        self.save()
        
        return str(self.balance)
    
    def increase_balance(self, amount):
        self.balance += Decimal(amount)
        self.save()
        
        return str(self.balance)
    
    class Meta:
        verbose_name = 'Account'
        verbose_name_plural = 'Accounts'
    
    
class Transfer(models.Model):#fait le
    sender_account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='sender_account')
    recipient_account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='recipient_account')
    amount = models.DecimalField(max_digits=18, decimal_places=3)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_transfer')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='transfer_created')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='transfer_updated', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    
    def __str__(self):
        return f"{self.sender_account.account_number} vers {self.recipient_account.account_number}"
    
    class Meta:
        verbose_name = 'Transfer'
        verbose_name_plural = 'Transfers'
    

class Currency(models.Model):
    name = models.CharField(max_length=20)
    code = models.CharField(max_length=10)
    status = models.SmallIntegerField(default=1, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='currency_created')
    updated_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='currency_updated', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return f"{self.name} - ({self.code})"
    
    class Meta:
        verbose_name = 'Currency'
        verbose_name_plural = 'Currencies'
      

backendapp/forms.py
from django import forms
from backendapp.models import *


class CategoryForm(forms.ModelForm):
    
    class Meta:
        model = Category
        exclude = ['status', 'created_by', 'updated_by', 'created_at', 'updated_at']
        
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Veuillez entrer un nom de categorie'}),
            'type': forms.Select(attrs={'class': 'form-select'}, choices=Category.TYPE_CHOISES),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Laisser une description...', 'style': 'height: 100px'}),
            'icon': forms.TextInput(attrs={'type': 'hidden'})
        }
    
    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        
        
class CurrencyForm(forms.ModelForm):
    
    class Meta:
        model = Currency
        exclude = ['status', 'created_by', 'updated_by', 'created_at', 'updated_at']
        
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Veuillez entrer un nom'}),
            'code': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Veuillez entrer le code'})
        }
        

class BudgetForm(forms.ModelForm):
    
    class Meta:
        model = Budget
        exclude = ['user', 'created_by', 'updated_by', 'created_at', 'updated_at']
        
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Veuillez entrer une désignation'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Laisser une description...', 'style': 'height: 100px'}),
            'total_amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'start_at': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'end_at': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'category': forms.Select(attrs={'class': 'form-select'}, choices=[(category.id, category.name) for category in Category.objects.filter(type='expense', status=1)])
        }
    
    
class TransactionForm(forms.ModelForm):
    
    class Meta:
        model = Transaction
        exclude = ['user', 'created_by', 'updated_by', 'created_at', 'updated_at']
        
        widgets = {
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Laisser une description...', 'style': 'height: 100px'}),
            'category': forms.Select({'class': 'form-select'}, choices=[]),
            'account': forms.Select({'class': 'form-select'}, choices=[]),
            'date': forms.DateTimeInput(attrs={'class': 'form-control input-with-bottom-line', 'id': 'dateEnd', 'type': 'date'}),
            'photo': forms.ClearableFileInput(
                attrs={'class': 'form-control input-with-bottom-line', 'type': 'file'})
        }
                
    def get_categories(self):
        return Category.objects.filter(status=1)
    
    
class AccountForm(forms.ModelForm):
    
    class Meta:
        model = Account
        exclude = ['status', 'user', 'created_by', 'updated_by', 'created_at', 'updated_at']
                
        widgets = {
            'name': forms.TextInput({'class': 'form-control', 'placeholder': 'Veuillez rentrez le nom (désignation)'}),
            'type': forms.Select(attrs={'class': 'form-select'}, choices=Account.TYPE_CHOICES),
            'balance': forms.NumberInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Laisser une description...', 'style': 'height: 100px'}),
            'currency': forms.Select(attrs={'class': 'form-select'}, choices=[(currency.id, currency.name) for currency in Currency.objects.filter(status=1)]),
        }
        
        
class TransferForm(forms.ModelForm):
    
    class Meta:
        model = Transfer
        exclude = ['user', 'created_by', 'updated_by', 'created_at', 'updated_at']
        
        widgets = {
            'sender_account': forms.Select(attrs={'class': 'form-select'}, choices=[]),
            'recipient_account': forms.Select(attrs={'class': 'form-select'}, choices=[]),
            'amount': forms.NumberInput(attrs={'class': 'form-control'})
        }

backendapp/templates/backendapp/pages/account/create-account.html
{% extends 'backendapp/base.html' %}
{% load static %}

{% block app_styles %}
<style>
    .icon-container {
        height: 250px;
        padding: 10px;
    }

    .icon-container > div {
        margin: 0 10px;
        padding: 10px;
        text-align: center;
    }

    .icon-container > div:hover {
        cursor: pointer;
        background-color: #ccc;
        color: #fff;
    }

    .icon-container > div > .feather {
        margin: 0 auto;
        width: 30px;
        height: 30px;
    }

    .icon-container > div > span {
        display: block;
    }
</style>
{% endblock app_styles %}

{% block main_content %}
<div class="container-fluid p-0">
    <div class="mb-3">
        <h1 class="h3 d-inline align-middle">
            Nouveau compte <i class="align-middle" data-feather="plus-circle"></i>
        </h1>
    </div>

    <div class="card">
        <div class="card-header d-flex flex-row-reverse">
            <a class="btn btn-primary" href="{% url 'accounts' %}">
                <i class="align-middle" data-feather="list"></i>
                Liste des comptes
                <i class="align-middle" data-feather="chevrons-right"></i>
            </a>
        </div>

        <div class="dropdown-divider"></div>

        {% include 'backendapp/partials/messages.html' %}

        <div class="card-body">
            <form id="account-form" method="post" action="{% url 'account-create' %}">
                {% csrf_token %}

                <div class="row mb-4">
                    <div class="col-md-6 mb-3">
                        <label for="id_category">Dévise:</label>
                        {{ form.currency }}
                    </div>

                    <div class="col-md-6 mb-3">
                        <label for="id_category">name:</label>
                        {{ form.name }}
                    </div>
        
                    <div class="col-md-6 mb-3">
                        <label for="id_user">Type de compte:</label>
                        {{ form.type }}
                    </div>
    
                    <div class="col-md-6 mb-3">
                        <label for="id_amount">Montant initial:</label>
                        {{ form.balance }}
                    </div>

                    <div class="mb-3 w-100">
                        <label for="id_description">Description:</label>
                        {{ form.description }}
                    </div>
                </div>

                <div class="d-flex flex-row-reverse">
                    <button type="submit" class="btn btn-primary btn-lg">Sauvegarder</button>
                </div>
            </form>
        </div>
    </div>
{% endblock main_content %}

{% block app_scripts %}
<script src="{% static 'backendapp/plugins/jquery-validation/jquery.validate.min.js' %}"></script>
<script src="{% static 'backendapp/plugins/jquery-validation/additional-methods.min.js' %}"></script>
<script src="{% static 'backendapp/plugins/jquery-validation/localization/messages_fr.min.js' %}"></script>

<script>
    $(document).ready(function() {
        $( "#account-form" ).validate( {
            rules: {
                currency: "required",
                name: {
                    required: true,
                    minlength: 3
                },
                type: "required",
                balance: {
                    required: true,
                    number: true
                }
            },
            messages: {
                currency: "Veuillez entrer la dévise à utiliser",
                name: {
                    required: "Veuillez entrer le nom du compte",
                    minlength: "Veuillez entrer au minimum 3 caractères"
                },
                type: "Veuillez entrer le type du compte",
                balance: {
                    required: "Veuillez entrer le solde initial",
                    number: "Veuillez entrer une valeur numérique valide"
                }
            },
            errorElement: "em",
            errorPlacement: function (error, element) {
                // Add `has-feedback` class to the parent div.form-group
                // in order to add icons to inputs
                element.addClass('is-invalid')

                if ( element.prop( "type" ) === "checkbox" ) {
                    error.insertAfter(element.parent( "label" ));
                } else {
                    error.insertAfter(element);
                }
            },
            success: function (label, element) {
                $(element).removeClass('is-invalid')
                $(element).addClass('is-valid')
            }
        } );
    })
</script>
{% endblock app_scripts %}

backendapp/templates/backendapp/pages/account/update-account.html
{% extends 'backendapp/base.html' %}
{% load static %}

{% block app_styles %}
<style>
    .icon-container {
        height: 250px;
        padding: 10px;
    }

    .icon-container > div {
        margin: 0 10px;
        padding: 10px;
        text-align: center;
    }

    .icon-container > div:hover {
        cursor: pointer;
        background-color: #ccc;
        color: #fff;
    }

    .icon-container > div > .feather {
        margin: 0 auto;
        width: 30px;
        height: 30px;
    }

    .icon-container > div > span {
        display: block;
    }
</style>
{% endblock app_styles %}

{% block main_content %}
<div class="container-fluid p-0">
    <div class="mb-3">
        <h1 class="h3 d-inline align-middle">
            Nouveau compte <i class="align-middle" data-feather="plus-circle"></i>
        </h1>
    </div>

    <div class="card">
        <div class="card-header d-flex flex-row-reverse">
            <a class="btn btn-primary" href="{% url 'accounts' %}">
                <i class="align-middle" data-feather="list"></i>
                Liste des comptes
                <i class="align-middle" data-feather="chevrons-right"></i>
            </a>
        </div>

        <div class="dropdown-divider"></div>

        {% include 'backendapp/partials/messages.html' %}

        <div class="card-body">
            <form id="account-form" method="post" action="{% url 'account-create' %}">
                {% csrf_token %}

                <div class="row mb-4">
                    <div class="col-md-6 mb-3">
                        <label for="id_category">Dévise:</label>
                        {{ form.currency }}
                    </div>

                    <div class="col-md-6 mb-3">
                        <label for="id_category">name:</label>
                        {{ form.name }}
                    </div>
        
                    <div class="col-md-6 mb-3">
                        <label for="id_user">Type de compte:</label>
                        {{ form.type }}
                    </div>
    
                    <div class="col-md-6 mb-3">
                        <label for="id_amount">Montant initial:</label>
                        {{ form.balance }}
                    </div>

                    <div class="mb-3 w-100">
                        <label for="id_description">Description:</label>
                        {{ form.description }}
                    </div>
                </div>

                <div class="d-flex flex-row-reverse">
                    <button type="submit" class="btn btn-primary btn-lg">Sauvegarder</button>
                </div>
            </form>
        </div>
    </div>
{% endblock main_content %}

{% block app_scripts %}
<script src="{% static 'backendapp/plugins/jquery-validation/jquery.validate.min.js' %}"></script>
<script src="{% static 'backendapp/plugins/jquery-validation/additional-methods.min.js' %}"></script>
<script src="{% static 'backendapp/plugins/jquery-validation/localization/messages_fr.min.js' %}"></script>

<script>
    $(document).ready(function() {
        $( "#account-form" ).validate( {
            rules: {
                currency: "required",
                name: {
                    required: true,
                    minlength: 3
                },
                type: "required",
                balance: {
                    required: true,
                    number: true
                }
            },
            messages: {
                currency: "Veuillez entrer la dévise à utiliser",
                name: {
                    required: "Veuillez entrer le nom du compte",
                    minlength: "Veuillez entrer au minimum 3 caractères"
                },
                type: "Veuillez entrer le type du compte",
                balance: {
                    required: "Veuillez entrer le solde initial",
                    number: "Veuillez entrer une valeur numérique valide"
                }
            },
            errorElement: "em",
            errorPlacement: function (error, element) {
                // Add `has-feedback` class to the parent div.form-group
                // in order to add icons to inputs
                element.addClass('is-invalid')

                if ( element.prop( "type" ) === "checkbox" ) {
                    error.insertAfter(element.parent( "label" ));
                } else {
                    error.insertAfter(element);
                }
            },
            success: function (label, element) {
                $(element).removeClass('is-invalid')
                $(element).addClass('is-valid')
            }
        } );
    })
</script>
{% endblock app_scripts %}